owner: MapsUntold
repo: status

sites:
  - name: Website
    url: https://mapsuntold.io
  - name: App
    url: https://app.mapsuntold.io
  - name: Dashboard
    url: https://dashboard.mapsuntold.io
  - name: Demo
    url: https://demo-mapsuntold.nl
  - name: Down test
    url: broken.mapsuntold.io

status-website:
  cname: status.mapsuntold.io
  logoUrl: https://www.mapsuntold.io/wp-content/uploads/2022/05/cropped-maps-untold-logo2-192x192.png
  name: Maps Untold
  introTitle: Maps Untold uptime monitor
  introMessage: Maps Untold uptime monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
